/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ajukan pertanyaan, terima jawaban lengkap
         * @description Balasan sekali kirim. Dipakai kotak uji coba admin (AD-6) dan test.
         *     Untuk antarmuka mahasiswa gunakan `/api/chat/stream` agar token muncul
         *     bertahap (FE-1).
         *
         *     Alurnya (PRD §7): sanitasi input -> pemeriksaan sensitif (FR-7) ->
         *     penulisan ulang query (FR-4) -> retrieval hibrida (FR-2) -> ambang
         *     penolakan (FR-3) -> deteksi topik berisiko (FR-6) -> generasi (FR-5).
         *
         *     LLM tidak dipanggil sama sekali bila `kind` bernilai `refusal` atau
         *     `support`.
         */
        post: operations["chat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ajukan pertanyaan, terima jawaban sebagai Server-Sent Events
         * @description Sama dengan `/api/chat`, tetapi jawabannya dialirkan sebagai SSE (FE-1).
         *
         *     Urutan event:
         *
         *     | Event | Kapan | Data |
         *     |---|---|---|
         *     | `status` | Segera, sebelum retrieval | `{"stage": "mencari dokumen"}` |
         *     | `message` | Setelah pipeline selesai | Objek `ChatResponse` utuh |
         *     | `done` | Terakhir | `{}` |
         *
         *     Event `status` yang mengisi indikator "mencari dokumen..." di FE-1.
         *     Klien harus menangani putusnya koneksi di tengah jalan: bila `done`
         *     tidak pernah tiba, perlakukan jawaban sebagai tidak lengkap dan jangan
         *     tampilkan sitasinya.
         */
        post: operations["chat_stream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Kirim umpan balik atas satu jawaban
         * @description FE-5: satu klik, tanpa modal. `catatan` opsional dan hanya muncul bila
         *     mahasiswa memilih mengisinya.
         *
         *     Mengirim ulang untuk `message_id` yang sama MENGGANTI umpan balik
         *     sebelumnya, supaya mahasiswa yang berubah pikiran dari 👍 ke 👎 tidak
         *     terhitung dua kali.
         *
         *     Rasio umpan balik positif adalah metrik PRD §3 (target >= 75%).
         *     Perhatikan anti-metriknya: volume percakapan tinggi bisa berarti sistem
         *     berguna, bisa juga berarti jawabannya buruk sehingga mahasiswa bertanya
         *     berulang kali.
         */
        post: operations["submit_feedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Saran pertanyaan untuk layar awal
         * @description FE-6: 4-5 contoh pertanyaan, ditampilkan sebelum mahasiswa mengetik.
         *
         *     Isinya WAJIB berasal dari hasil survei (PRD §15 butir 1), bukan karangan
         *     pengembang. Menampilkan pertanyaan yang tidak pernah benar-benar
         *     ditanyakan orang akan mengarahkan mahasiswa ke jalur yang salah sejak
         *     layar pertama.
         */
        get: operations["list_suggestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Unduh atau tampilkan PDF sumber
         * @description Tujuan klik pada kartu sitasi (FE-2). Nomor halaman TIDAK dikirim ke
         *     server -- klien membukanya lewat fragment PDF viewer
         *     (`.../file#page=12`) atau meneruskannya ke react-pdf.
         *
         *     Hanya dokumen `is_active = true` yang dilayani. Dokumen yang sudah
         *     dinonaktifkan mengembalikan 404, supaya tautan lama pada percakapan
         *     lampau tidak diam-diam menyajikan informasi kedaluwarsa.
         *
         *     **Balasannya bergantung pada `STORAGE_BACKEND`, jadi klien harus siap
         *     menerima keduanya:**
         *
         *     | Backend | Balasan |
         *     |---|---|
         *     | `s3` (S3 / R2) | `307` ke presigned URL atau URL publik bucket |
         *     | `local` | `200` dengan isi PDF langsung |
         *
         *     Pengalihan dipilih untuk S3 supaya PDF mengalir dari object storage ke
         *     peramban tanpa melewati proses API. Panduan akademik bisa puluhan
         *     megabita; menyalurkannya lewat API hanya menghabiskan memori dan
         *     koneksi tanpa manfaat apa pun.
         *
         *     Setel `fetch(..., { redirect: 'follow' })` atau cukup pasang URL ini
         *     sebagai `src` — peramban mengikuti pengalihan dengan sendirinya. Jangan
         *     cache URL hasil pengalihan: presigned URL kedaluwarsa (default 15
         *     menit) dan harus diminta ulang lewat endpoint ini.
         */
        get: operations["get_document_file"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Dipakai Uptime Kuma (PRD §10).
         *
         *     Tetap 200 saat kill switch aktif. Kill switch adalah keputusan operator,
         *     bukan kegagalan sistem; melaporkannya sebagai unhealthy akan membuat
         *     monitoring membanjiri alert justru ketika insiden sedang ditangani.
         *     Pantau `chat_enabled` bila ingin tahu layanan chat hidup atau tidak.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login admin
         * @description AD-1. Mengembalikan JWT berumur `ADMIN_TOKEN_TTL_MINUTES` (default 8 jam).
         *
         *     Balasan gagal sengaja tidak membedakan "email tidak terdaftar" dari
         *     "kata sandi salah", supaya tidak bisa dipakai memetakan siapa saja yang
         *     punya akun admin.
         */
        post: operations["admin_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daftar dokumen
         * @description AD-2. Setiap baris membawa `stale` untuk badge peringatan: dokumen yang
         *     lebih dari 6 bulan tidak diperbarui, atau sudah lewat `valid_until`.
         *
         *     PRD §12 menyebut "dokumen tidak diupdate" sebagai risiko dengan dampak
         *     sistem menyebarkan info kedaluwarsa secara aktif. Badge ini mitigasinya,
         *     jadi jangan sembunyikan di balik filter.
         *
         *     Staf/dosen hanya melihat dokumen unitnya; `total` dan `jumlah_stale` pun
         *     dihitung atas unit itu. Membuka, mengubah, menghapus, atau mengunggah
         *     dokumen unit lain dijawab 403. Nama unit dibandingkan tanpa peduli huruf
         *     besar dan spasi berlebih.
         */
        get: operations["list_documents"];
        put?: never;
        /**
         * Unggah dokumen baru
         * @description AD-3. Drag & drop + form metadata. Pemrosesan berjalan sinkron: unggah,
         *     ekstraksi, chunking, embedding, simpan -- semuanya dalam satu transaksi.
         *     Dokumen yang gagal di tengah jalan tidak meninggalkan chunk yatim.
         *
         *     PDF hasil scan tanpa lapisan teks ditolak dengan 422 (FR-1). Ini bukan
         *     kerewelan: chunk kosong tetap masuk indeks dan tidak pernah terambil,
         *     sehingga dokumen tampak terpasang padahal tidak berfungsi.
         *
         *     Bahasa pesan galat ke admin harus non-teknis (PRD §9).
         */
        post: operations["upload_document"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        /** Detail satu dokumen */
        get: operations["get_document"];
        put?: never;
        post?: never;
        /**
         * Hapus dokumen beserta seluruh chunk-nya
         * @description Permanen dan tidak dapat dibatalkan. Frontend WAJIB meminta konfirmasi
         *     (PRD §9: semua aksi destruktif butuh konfirmasi).
         *
         *     Untuk sekadar mengeluarkan dokumen dari indeks, pakai
         *     `PATCH { "is_active": false }` -- itu dapat dikembalikan.
         */
        delete: operations["delete_document"];
        options?: never;
        head?: never;
        /**
         * Perbarui metadata atau status aktif
         * @description Mengubah `valid_until` atau `is_active` langsung mempengaruhi retrieval
         *     pada permintaan berikutnya -- filter dokumen aktif dievaluasi di dalam
         *     WHERE setiap query (FR-2), bukan di-cache.
         *
         *     Menonaktifkan dokumen TIDAK menghapus chunk-nya, sehingga dapat
         *     dikembalikan bila ternyata keliru.
         *
         *     `updated_at` diperbarui saat `judul`, `unit`, `tahun_berlaku`, atau
         *     `valid_until` berubah -- itu dianggap peninjauan dan menghapus badge
         *     usia AD-2. Mengubah `is_active` saja tidak: menyalakan ulang dokumen
         *     lama tidak boleh menghapus peringatannya.
         */
        patch: operations["update_document"];
        trace?: never;
    };
    "/api/admin/documents/{document_id}/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pratinjau hasil chunking
         * @description AD-3 menyebut "preview hasil chunk". Gunanya konkret: admin dapat
         *     melihat apakah tabel atau daftar bernomor terpotong di tengah, yang
         *     merupakan penyebab paling umum jawaban benar tetapi tidak lengkap.
         */
        get: operations["list_document_chunks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/unanswered": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pertanyaan tak terjawab, dikelompokkan
         * @description AD-4. PRD menyebut halaman ini "menentukan sistem membaik atau stagnan"
         *     dan meminta ia ditempatkan menonjol di navigasi.
         *
         *     Pertanyaan yang mirip dikelompokkan beserta frekuensinya, sehingga admin
         *     melihat "12 mahasiswa menanyakan ini" alih-alih 12 baris terpisah.
         *
         *     Kemiripan diukur dari kata yang sama setelah kata tanya dan sapaan
         *     dibuang (bukan embedding), jadi dapat dijelaskan dan tidak memanggil API
         *     berbayar. Pertanyaan yang sudah dan belum ditindaklanjuti tidak pernah
         *     berada di kelompok yang sama. `limit` dan `offset` berlaku atas
         *     kelompok, bukan atas baris.
         */
        get: operations["list_unanswered"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/unanswered/{unanswered_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Tandai pertanyaan sudah ditindaklanjuti
         * @description Ditandai `resolved` setelah dokumen yang menjawabnya diunggah. Ini
         *     bukan sekadar penanda kerapian -- selisih antara pertanyaan masuk dan
         *     pertanyaan terselesaikan adalah ukuran apakah sistem benar-benar
         *     membaik.
         *
         *     Satu PATCH mengubah satu baris. Untuk menandai satu kelompok AD-4,
         *     kirim PATCH untuk setiap id di `UnansweredGroup.ids`.
         */
        patch: operations["resolve_unanswered"];
        trace?: never;
    };
    "/api/admin/test-query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Uji coba retrieval, tampilkan chunk dan skornya
         * @description AD-6. Berbeda dari `/api/chat`: balasan ikut membawa chunk yang terambil
         *     beserta skor mentah tiap sumber (vector dan fulltext) dan skor RRF.
         *
         *     Ini alat diagnosa utama saat ada laporan "jawabannya salah". Skor mentah
         *     yang ditampilkan, bukan skor RRF, karena skor RRF hanya mencerminkan
         *     peringkat -- chunk terbaik dari sekumpulan chunk tak relevan tetap
         *     mendapat skor RRF tertinggi.
         *
         *     Tidak tunduk pada kill switch (admin perlu mendiagnosis justru saat
         *     layanan dimatikan) dan TIDAK dicatat ke log percakapan, supaya uji coba
         *     tidak mencemari AD-4 maupun AD-5. LLM tetap dipanggil bila lolos ambang.
         */
        post: operations["admin_test_query"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Statistik penggunaan dan biaya
         * @description AD-5. Termasuk `biaya_usd_berjalan` -- PRD §12 menandai biaya API
         *     membengkak sebagai risiko dengan dampak layanan mati mendadak.
         *
         *     `total_percakapan` disajikan sebagai konteks, bukan sebagai ukuran
         *     keberhasilan. PRD §3 menetapkannya sebagai anti-metrik.
         *
         *     Tanpa parameter: 30 hari terakhir sampai hari ini. Hari dihitung menurut
         *     `TIMEZONE` server, bukan UTC. Rentang paling panjang 366 hari.
         */
        get: operations["admin_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/kill-switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Status kill switch
         * @description Semua level boleh membaca, supaya banner "layanan dimatikan" tampil untuk semua admin.
         */
        get: operations["get_kill_switch"];
        put?: never;
        /**
         * Nyalakan atau matikan kill switch
         * @description FR-9. Mematikan layanan chat dengan cepat saat insiden, tanpa menunggu
         *     deploy ulang.
         *
         *     `alasan` wajib diisi saat menyalakan: insiden tanpa catatan alasan tidak
         *     bisa diaudit setelahnya. Dashboard admin tetap hidup saat kill switch
         *     aktif -- justru saat itulah admin perlu masuk untuk melihat apa yang
         *     terjadi.
         *
         *     PRD §14 mensyaratkan kill switch DIUJI sebelum rilis, bukan sekadar ada.
         */
        post: operations["set_kill_switch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Akun yang sedang masuk
         * @description Level dan unit menurut database SAAT INI, bukan isi token. Dashboard
         *     memakainya untuk memilih menu yang tampil; penegakan aksesnya tetap di
         *     server.
         */
        get: operations["get_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ganti kata sandi sendiri
         * @description Dipakai terutama setelah menerima kata sandi sementara dari superadmin.
         *     Semua sesi lain akun ini langsung berakhir. Balasan membawa token baru
         *     untuk sesi yang dipakai mengganti, jadi tidak perlu masuk ulang.
         */
        post: operations["change_my_password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daftar akun dashboard */
        get: operations["list_users"];
        put?: never;
        /**
         * Buat akun dashboard
         * @description Kata sandi dibangkitkan server dan dikembalikan SEKALI sebagai
         *     `password_sementara`. Superadmin tidak memilih kata sandi orang lain,
         *     sehingga tidak ada yang mengetahui kata sandi akhir selain pemiliknya
         *     setelah ia menggantinya.
         */
        post: operations["create_user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Hapus akun dashboard
         * @description Permanen; frontend WAJIB meminta konfirmasi. Untuk menghentikan akses
         *     sementara, nonaktifkan saja. Dokumen unggahan akun ini tidak ikut
         *     terhapus.
         */
        delete: operations["delete_user"];
        options?: never;
        head?: never;
        /**
         * Ubah nama, level, unit, atau status aktif
         * @description Berlaku pada permintaan berikutnya akun tersebut. Ditolak 409 bila:
         *     superadmin menurunkan level atau menonaktifkan dirinya sendiri,
         *     superadmin aktif terakhir disingkirkan, atau level staf tanpa unit.
         */
        patch: operations["update_user"];
        trace?: never;
    };
    "/api/admin/users/{user_id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Atur ulang kata sandi akun lain
         * @description Membangkitkan kata sandi sementara baru (ditampilkan sekali) dan
         *     mengakhiri semua sesi akun itu. Untuk akun sendiri gunakan
         *     `POST /api/admin/me/password`.
         */
        post: operations["reset_user_password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Menentukan cara frontend menampilkan balasan. Hanya `answer` yang
         *     membawa sitasi; `refusal`, `support`, dan `smalltalk` tidak pernah.
         * @enum {string}
         */
        OutcomeKind: "answer" | "refusal" | "support" | "smalltalk";
        TurnIn: {
            /** @description `system` sengaja tidak diterima -- itu jalur injeksi. */
            role: string;
            konten: string;
        };
        ChatRequest: {
            /**
             * @description Pertanyaan apa adanya. Server yang menyanitasi dan membungkusnya
             *     dengan delimiter; klien tidak perlu (dan tidak boleh) ikut memproses.
             */
            question: string;
            /**
             * @description Dibangkitkan klien, disimpan di localStorage. JANGAN isi dengan NIM,
             *     email, atau apa pun yang dapat mengenali orang (PRD §11).
             */
            session_id: string;
            /**
             * @description Riwayat percakapan. Hanya 3 pesan terakhir yang dipakai untuk
             *     penulisan ulang query (FR-4); mengirim lebih banyak tidak menambah
             *     ketepatan tetapi menaikkan biaya.
             * @default []
             */
            history: components["schemas"]["TurnIn"][];
        };
        /**
         * @description Isi kartu sitasi FE-2. Cukup untuk membuka PDF tepat di halamannya:
         *     `GET /api/documents/{document_id}/file#page={halaman}`.
         */
        CitationOut: {
            judul: string;
            halaman: number;
            /** Format: uuid */
            document_id: string;
            /** @description Lintasan internal. Untuk ditampilkan, bukan untuk diakses langsung. */
            file_path: string;
        };
        /** @description Isi banner eskalasi FE-3. */
        ContactOut: {
            unit: string;
            jam_layanan: string;
            kontak: string;
        };
        ChatResponse: {
            kind: components["schemas"]["OutcomeKind"];
            /**
             * Format: uuid
             * @description Id jawaban di tabel `messages`, dipakai `POST /api/feedback`. Bernilai
             *     null bila pencatatan ke database gagal (jawaban tetap terkirim) --
             *     frontend harus menyembunyikan tombol 👍/👎 saat null, bukan mengirim
             *     id kosong.
             */
            message_id?: string | null;
            text: string;
            /**
             * @description Hanya dokumen yang benar-benar dikutip di `text`, urut kemunculan --
             *     bukan seluruh chunk yang terambil retrieval. Retrieval mengambil
             *     beberapa chunk sebagai konteks LLM; menampilkan semuanya sebagai
             *     "Sumber" memaksa mahasiswa menebak kartu mana yang relevan.
             *
             *     Sitasi ke dokumen di luar konteks (sumber karangan) tidak pernah
             *     ikut: tautannya buntu. Jawaban tanpa satu pun penanda sitasi jatuh
             *     kembali ke seluruh chunk terambil, supaya verifikasi tetap mungkin.
             *
             *     Selalu kosong bila `kind` bukan `answer`.
             * @default []
             */
            citations: components["schemas"]["CitationOut"][];
            /** @default [] */
            contacts: components["schemas"]["ContactOut"][];
            /**
             * @description Tampilkan banner FE-3 bila true.
             * @default false
             */
            escalated: boolean;
            /**
             * @description Skor kemiripan mentah tertinggi, bukan skor RRF. Jangan ditampilkan
             *     ke mahasiswa -- angka ini untuk AD-6 dan kalibrasi ambang.
             */
            top_score?: number | null;
        };
        FeedbackRequest: {
            /** Format: uuid */
            message_id: string;
            /** @description true = 👍, false = 👎 */
            helpful: boolean;
            catatan?: string | null;
        };
        Suggestion: {
            teks: string;
        };
        HealthResponse: {
            /** @constant */
            status: "ok";
            /** @description false berarti kill switch aktif; proses tetap sehat. */
            chat_enabled: boolean;
            kill_switch_reason?: string | null;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        TokenResponse: {
            access_token: string;
            /** @constant */
            token_type: "bearer";
        };
        Document: {
            /** Format: uuid */
            id: string;
            judul: string;
            unit: string;
            tahun_berlaku?: number | null;
            /**
             * Format: date
             * @description null berarti berlaku tanpa batas. Lewat tanggal ini, dokumen
             *     berhenti terambil retrieval secara otomatis (FR-2) -- tidak perlu
             *     ada yang ingat menonaktifkannya.
             */
            valid_until?: string | null;
            /** Format: date-time */
            updated_at: string;
            is_active: boolean;
            jumlah_chunk: number;
            /**
             * @description Badge peringatan AD-2: lebih dari 6 bulan tidak diperbarui, atau
             *     sudah lewat `valid_until`.
             */
            stale: boolean;
            /**
             * @description Email admin pengunggah. PRD §12 memitigasi dokumen usang lewat admin
             *     bernama -- badge tanpa nama penanggung jawab mudah diabaikan.
             */
            uploaded_by?: string | null;
        };
        DocumentPage: {
            items: components["schemas"]["Document"][];
            /** @description Jumlah dokumen yang cocok dengan filter, untuk paginasi. */
            total: number;
            /**
             * @description Dokumen AKTIF yang perlu ditinjau, tidak terpengaruh filter. Untuk
             *     lencana angka di navigasi AD-2. Dokumen nonaktif tidak dihitung
             *     karena sudah tidak terambil retrieval.
             */
            jumlah_stale: number;
        };
        DocumentUpload: {
            /**
             * Format: binary
             * @description Berkas PDF.
             */
            file: string;
            judul: string;
            unit: string;
            tahun_berlaku?: number | null;
            /** Format: date */
            valid_until?: string | null;
        };
        /** @description Hanya field yang dikirim yang diubah. */
        DocumentUpdate: {
            judul?: string;
            unit?: string;
            tahun_berlaku?: number | null;
            /**
             * Format: date
             * @description Kirim null untuk menjadikan dokumen berlaku tanpa batas.
             */
            valid_until?: string | null;
            is_active?: boolean;
        };
        IngestionResult: {
            /** Format: uuid */
            document_id: string;
            jumlah_halaman: number;
            jumlah_chunk: number;
        };
        Chunk: {
            /** Format: uuid */
            id: string;
            konten: string;
            halaman: number;
            urutan: number;
        };
        UnansweredUpdate: {
            resolved: boolean;
        };
        UnansweredGroup: {
            /**
             * @description Seluruh baris `unanswered` dalam kelompok. Menandai kelompok selesai
             *     berarti PATCH `/api/admin/unanswered/{id}` untuk setiap id.
             */
            ids: string[];
            /** @description Satu pertanyaan mewakili kelompok, apa adanya seperti diketik. */
            contoh_pertanyaan: string;
            jumlah: number;
            /**
             * @description Rata-rata skor tertinggi kelompok ini. Nilai yang mendekati ambang
             *     menandakan dokumennya mungkin sudah ada tetapi retrieval-nya meleset;
             *     nilai sangat rendah menandakan dokumennya memang belum ada.
             */
            top_score_rata2?: number | null;
            /** Format: date-time */
            terakhir_ditanyakan: string;
            resolved: boolean;
        };
        /** @description Rincian diagnosa AD-6. */
        RetrievedChunk: {
            /** Format: uuid */
            chunk_id: string;
            /** Format: uuid */
            document_id?: string | null;
            judul: string;
            halaman: number;
            konten: string;
            /** @description Skor gabungan. Berbasis peringkat -- jangan pakai untuk menilai relevansi. */
            rrf_score: number;
            /**
             * @description Skor mentah per sumber. Ini yang menentukan penolakan (FR-3). Kunci
             *     sebuah sumber hanya ada bila sumber itu menemukan chunk ini: chunk
             *     yang hanya ditemukan fulltext tidak punya `vector`.
             */
            raw_scores: {
                /** @description Cosine similarity, 0..1. */
                vector?: number;
                /** @description `ts_rank` Postgres. */
                fulltext?: number;
            };
            /** @description Peringkat 1-based di tiap sumber. Kunci absen seperti `raw_scores`. */
            ranks: {
                vector?: number;
                fulltext?: number;
            };
        };
        TestQueryRequest: {
            question: string;
            /**
             * @description Timpa ambang vektor untuk uji coba ini saja, untuk mencari nilai yang
             *     pas. Tidak mengubah ambang yang berlaku bagi mahasiswa.
             */
            vector_threshold?: number | null;
        };
        /** @description Ambang yang benar-benar dipakai pada uji coba ini (FR-3). */
        ThresholdValues: {
            vector: number;
            fulltext: number;
        };
        TestQueryResponse: {
            kind: components["schemas"]["OutcomeKind"];
            text: string;
            rewritten_query?: string | null;
            /** @description Tetap terisi saat ditolak -- justru itu yang perlu dilihat saat diagnosa. */
            retrieved: components["schemas"]["RetrievedChunk"][];
            /** @description null bila pertanyaan dialihkan ke konseling (FR-7) sebelum retrieval. */
            decision: {
                /** @enum {string} */
                decision: "proceed" | "refuse";
                /** @enum {string} */
                reason: "ok" | "no_results" | "below_threshold";
                top_vector_score?: number | null;
                top_lexical_score?: number | null;
            } | null;
            ambang: components["schemas"]["ThresholdValues"];
            /** @description Kontak yang akan dilihat mahasiswa untuk pertanyaan yang sama (FE-3, FE-4). */
            contacts: components["schemas"]["ContactOut"][];
            escalated: boolean;
            latency_ms: number;
            /** @description Penghubung ke trace LangSmith. Selalu null sampai tracing dipasang. */
            langsmith_run_id?: string | null;
        };
        DailyVolume: {
            /** Format: date */
            tanggal: string;
            jumlah: number;
        };
        TopicCount: {
            /**
             * @description Nilai `RiskTopic` (FR-6): `deadline`, `syarat_kelulusan`,
             *     `pembayaran`, `sanksi`, `drop_out`. Label tampilan diserahkan ke
             *     frontend.
             */
            topik: string;
            jumlah: number;
        };
        /** @description Jumlah balasan per `kind` dalam rentang. */
        KindBreakdown: {
            answer: number;
            refusal: number;
            support: number;
            /**
             * @description Sapaan dan basa-basi. Bukan pertanyaan administrasi -- jangan
             *     disandingkan dengan `answer` seolah keduanya setara.
             */
            smalltalk: number;
        };
        Stats: {
            /** Format: date */
            sejak: string;
            /** Format: date */
            sampai: string;
            /**
             * @description Konteks, BUKAN ukuran keberhasilan. PRD §3 menetapkannya sebagai
             *     anti-metrik: volume tinggi bisa berarti jawabannya buruk sehingga
             *     mahasiswa bertanya berulang kali. Satu percakapan = pesan dari
             *     `session_id` yang sama dengan jeda di bawah 30 menit.
             */
            total_percakapan: number;
            total_pertanyaan: number;
            rincian_jenis: components["schemas"]["KindBreakdown"];
            jumlah_feedback: number;
            /** @description Target PRD §3 >= 0.75. null bila belum ada umpan balik. */
            rasio_feedback_positif: number | null;
            /** @description Target PRD §3 < 0.15. null bila belum ada pertanyaan. */
            rasio_tak_terjawab: number | null;
            /** @description Satu entri per hari dalam rentang, termasuk hari tanpa pertanyaan. */
            volume_harian: components["schemas"]["DailyVolume"][];
            topik_populer: components["schemas"]["TopicCount"][];
            /** @description Estimasi dari token terpakai, bukan dari API penagihan. */
            biaya_usd_berjalan: number;
            /**
             * @description Jawaban yang memanggil LLM tetapi modelnya belum punya tarif di
             *     `app/observability/costs.py`. Lebih dari nol berarti
             *     `biaya_usd_berjalan` KURANG dari biaya sebenarnya -- tampilkan
             *     sebagai peringatan, jangan sebagai biaya nol.
             */
            pesan_tanpa_estimasi_biaya: number;
            /**
             * @description Persentil 95 waktu proses jawaban lengkap. Target PRD §11 (first
             *     token < 3000 ms) diukur di LangSmith; angka ini batas atasnya.
             */
            latency_p95_ms: number | null;
        };
        KillSwitchRequest: {
            engaged: boolean;
            /** @description Wajib diisi (bukan spasi saja) saat `engaged` true. Diabaikan saat false. */
            alasan?: string | null;
        };
        KillSwitchState: {
            engaged: boolean;
            reason?: string | null;
            /** Format: date-time */
            engaged_at?: string | null;
            /**
             * @description Email admin yang menyalakan, atau `konfigurasi server` bila
             *     dinyalakan lewat `KILL_SWITCH_ENABLED`.
             */
            engaged_by?: string | null;
        };
        /**
         * @description Level bertingkat; setiap level mencakup hak level di bawahnya. `staf`
         *     ditampilkan sebagai "Staf/Dosen".
         * @enum {string}
         */
        AdminRole: "staf" | "admin" | "superadmin";
        /** @description Akun dashboard. Hash kata sandi tidak pernah dikirim. */
        AdminUser: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["AdminRole"];
            is_active: boolean;
            nama?: string | null;
            /**
             * @description Wajib untuk `staf`: membatasi dokumen yang dapat dikelola. Untuk level
             *     lain hanya keterangan.
             */
            unit?: string | null;
            /** Format: date-time */
            created_at?: string | null;
            /** Format: date-time */
            last_login_at?: string | null;
        };
        AdminUserCreate: {
            /** Format: email */
            email: string;
            role: components["schemas"]["AdminRole"];
            nama?: string | null;
            /** @description Wajib bila `role` bernilai `staf`. */
            unit?: string | null;
        };
        /** @description Hanya field yang dikirim yang diubah. Field tak dikenal ditolak. */
        AdminUserUpdate: {
            nama?: string | null;
            role?: components["schemas"]["AdminRole"];
            unit?: string | null;
            is_active?: boolean;
        };
        AdminUserCreated: {
            user: components["schemas"]["AdminUser"];
            /** @description Ditampilkan SEKALI dan tidak dapat diambil lagi. */
            password_sementara: string;
        };
        TemporaryPassword: {
            password_sementara: string;
        };
        PasswordChange: {
            password_lama: string;
            /** @description Maksimal 72 byte (batas bcrypt). */
            password_baru: string;
        };
        Error: {
            /**
             * @description Kalimat siap tampil. Untuk endpoint admin bahasanya non-teknis
             *     (PRD §9: "dokumen sedang diproses", bukan "embedding in progress").
             */
            detail: string;
        };
        ValidationError: {
            loc: (string | number)[];
            msg: string;
            type: string;
        };
        HTTPValidationError: {
            detail?: components["schemas"]["ValidationError"][];
        };
    };
    responses: {
        /** @description Body permintaan tidak sah */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["HTTPValidationError"];
            };
        };
        /** @description Melebihi batas laju (FR-9) */
        RateLimited: {
            headers: {
                /** @description Detik sampai boleh mencoba lagi. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "detail": "Terlalu banyak pertanyaan dalam waktu singkat. Coba lagi sebentar lagi."
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description Layanan chat dimatikan operator (FR-9). Frontend menampilkan `detail`
         *     apa adanya -- kalimatnya sudah memuat kontak manusia sebagai jalan keluar.
         */
        KillSwitchAktif: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "detail": "Layanan chat sedang dinonaktifkan sementara. Silakan hubungi Biro Administrasi Akademik pada jam kerja."
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description Token tidak ada, tidak valid, atau kedaluwarsa; akun sudah dinonaktifkan
         *     atau dihapus; atau kata sandi sudah diganti sejak token terbit. Frontend
         *     menghapus sesi dan kembali ke halaman login.
         */
        TidakBerwenang: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description Level akun di bawah `x-min-role` operasi ini, atau staf/dosen menyentuh
         *     dokumen unit lain. Sesi tetap berlaku; `detail` siap tampil.
         */
        Terlarang: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Sumber daya tidak ditemukan */
        TidakDitemukan: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /**
         * @description Pembatasan laju per sesi (FR-9). Bila tidak dikirim, sistem jatuh ke
         *     pembatasan per IP -- yang di jaringan kampus dipakai bersama ratusan
         *     mahasiswa, sehingga jauh lebih mudah kena batas. Kirimkan nilai yang
         *     sama dengan `session_id` di body.
         */
        SessionIdHeader: string;
        Limit: number;
        Offset: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    chat: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Pembatasan laju per sesi (FR-9). Bila tidak dikirim, sistem jatuh ke
                 *     pembatasan per IP -- yang di jaringan kampus dipakai bersama ratusan
                 *     mahasiswa, sehingga jauh lebih mudah kena batas. Kirimkan nilai yang
                 *     sama dengan `session_id` di body.
                 */
                "X-Session-Id"?: components["parameters"]["SessionIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /**
             * @description Selalu 200 selama pertanyaannya sah, termasuk saat sistem menolak
             *     menjawab. Penolakan adalah hasil yang sah, bukan kegagalan.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["KillSwitchAktif"];
        };
    };
    chat_stream: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Pembatasan laju per sesi (FR-9). Bila tidak dikirim, sistem jatuh ke
                 *     pembatasan per IP -- yang di jaringan kampus dipakai bersama ratusan
                 *     mahasiswa, sehingga jauh lebih mudah kena batas. Kirimkan nilai yang
                 *     sama dengan `session_id` di body.
                 */
                "X-Session-Id"?: components["parameters"]["SessionIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Aliran SSE */
            200: {
                headers: {
                    "Cache-Control"?: "no-cache";
                    /** @description Mencegah reverse proxy menahan aliran sampai selesai. */
                    "X-Accel-Buffering"?: "no";
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example event: status
                     *     data: {"stage": "mencari dokumen"}
                     *
                     *     event: message
                     *     data: {"kind": "answer", "text": "Pengisian KRS dibuka 1-7 Agustus 2025 [Panduan Akademik 2025, hal. 12].", "citations": [{"judul": "Panduan Akademik 2025", "halaman": 12, "document_id": "3f1a...", "file_path": "storage/documents/3f1a....pdf"}], "contacts": [], "escalated": false, "top_score": 0.82}
                     *
                     *     event: done
                     *     data: {}
                     */
                    "text/event-stream": string;
                };
            };
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["KillSwitchAktif"];
        };
    };
    submit_feedback: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Pembatasan laju per sesi (FR-9). Bila tidak dikirim, sistem jatuh ke
                 *     pembatasan per IP -- yang di jaringan kampus dipakai bersama ratusan
                 *     mahasiswa, sehingga jauh lebih mudah kena batas. Kirimkan nilai yang
                 *     sama dengan `session_id` di body.
                 */
                "X-Session-Id"?: components["parameters"]["SessionIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Tercatat. Tidak ada isi balasan -- FE-5 tidak menampilkan konfirmasi. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["TidakDitemukan"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
        };
    };
    list_suggestions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar saran */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "teks": "Kapan pengisian KRS dibuka?"
                     *       },
                     *       {
                     *         "teks": "Bagaimana cara mengajukan cuti kuliah?"
                     *       },
                     *       {
                     *         "teks": "Apa saja syarat wisuda?"
                     *       },
                     *       {
                     *         "teks": "Bagaimana cara minta surat keterangan aktif kuliah?"
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["Suggestion"][];
                };
            };
        };
    };
    get_document_file: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Berkas PDF (hanya saat `STORAGE_BACKEND=local`) */
            200: {
                headers: {
                    /** @description `inline` agar terbuka di viewer, bukan terunduh. */
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            /** @description Pengalihan ke object storage (saat `STORAGE_BACKEND=s3`). */
            307: {
                headers: {
                    /** @description Presigned URL berumur pendek, atau URL publik bucket. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["TidakDitemukan"];
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Proses hidup */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    admin_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Berhasil */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Email atau kata sandi salah */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Email atau kata sandi salah"
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
            /**
             * @description Kata sandi benar, tetapi akun sudah dinonaktifkan superadmin. Hanya
             *     diberitahukan setelah kata sandi terbukti benar, jadi status akun tidak
             *     bocor ke orang yang sekadar menebak email.
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    list_documents: {
        parameters: {
            query?: {
                include_inactive?: boolean;
                /** @description Saring hanya dokumen yang perlu ditinjau. */
                only_stale?: boolean;
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar dokumen */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentPage"];
                };
            };
            401: components["responses"]["TidakBerwenang"];
            403: components["responses"]["Terlarang"];
        };
    };
    upload_document: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["DocumentUpload"];
            };
        };
        responses: {
            /** @description Dokumen terpasang dan terindeks */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionResult"];
                };
            };
            401: components["responses"]["TidakBerwenang"];
            403: components["responses"]["Terlarang"];
            /** @description Berkas melebihi `MAX_UPLOAD_MB` */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Berkas ditolak. `detail` sudah berupa kalimat siap tampil untuk admin. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /**
             * @description Layanan luar gagal: penyimpanan dokumen atau API AI. `detail` berisi
             *     kalimat siap tampil yang menyarankan mencoba lagi; rinciannya hanya
             *     ada di log server.
             */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    get_document: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detail dokumen */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            401: components["responses"]["TidakBerwenang"];
            403: components["responses"]["Terlarang"];
            404: components["responses"]["TidakDitemukan"];
        };
    };
    delete_document: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Terhapus */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["TidakBerwenang"];
            403: components["responses"]["Terlarang"];
            404: components["responses"]["TidakDitemukan"];
        };
    };
    update_document: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentUpdate"];
            };
        };
        responses: {
            /** @description Tersimpan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            401: components["responses"]["TidakBerwenang"];
            403: components["responses"]["Terlarang"];
            404: components["responses"]["TidakDitemukan"];
            422: components["responses"]["ValidationError"];
        };
    };
    list_document_chunks: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar chunk terurut */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chunk"][];
                };
            };
            401: components["responses"]["TidakBerwenang"];
            403: components["responses"]["Terlarang"];
            404: components["responses"]["TidakDitemukan"];
        };
    };
    list_unanswered: {
        parameters: {
            query?: {
                /** @description Kosongkan untuk menampilkan keduanya. */
                resolved?: boolean;
                sejak?: string;
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Kelompok pertanyaan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "ids": [
                     *           "0b6f2c1e-3a4d-4e5f-9a8b-7c6d5e4f3a2b",
                     *           "1c7a3d2f-4b5e-4f60-8b9c-8d7e6f5a4b3c"
                     *         ],
                     *         "contoh_pertanyaan": "Bagaimana cara mengurus surat keterangan lulus?",
                     *         "jumlah": 12,
                     *         "top_score_rata2": 0.21,
                     *         "terakhir_ditanyakan": "2026-09-09T14:22:11Z",
                     *         "resolved": false
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["UnansweredGroup"][];
                };
            };
            401: components["responses"]["TidakBerwenang"];
            403: components["responses"]["Terlarang"];
        };
    };
    resolve_unanswered: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                unanswered_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnansweredUpdate"];
            };
        };
        responses: {
            /** @description Tersimpan */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["TidakBerwenang"];
            403: components["responses"]["Terlarang"];
            404: components["responses"]["TidakDitemukan"];
        };
    };
    admin_test_query: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestQueryRequest"];
            };
        };
        responses: {
            /** @description Hasil beserta rincian retrieval */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestQueryResponse"];
                };
            };
            401: components["responses"]["TidakBerwenang"];
            403: components["responses"]["Terlarang"];
            422: components["responses"]["ValidationError"];
        };
    };
    admin_stats: {
        parameters: {
            query?: {
                sejak?: string;
                sampai?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Statistik */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stats"];
                };
            };
            401: components["responses"]["TidakBerwenang"];
            403: components["responses"]["Terlarang"];
            /** @description Rentang tanggal tidak sah (terbalik atau terlalu panjang) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    get_kill_switch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KillSwitchState"];
                };
            };
            401: components["responses"]["TidakBerwenang"];
            403: components["responses"]["Terlarang"];
        };
    };
    set_kill_switch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KillSwitchRequest"];
            };
        };
        responses: {
            /** @description Status baru */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KillSwitchState"];
                };
            };
            401: components["responses"]["TidakBerwenang"];
            403: components["responses"]["Terlarang"];
            422: components["responses"]["ValidationError"];
        };
    };
    get_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Akun */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
            401: components["responses"]["TidakBerwenang"];
        };
    };
    change_my_password: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChange"];
            };
        };
        responses: {
            /** @description Tersimpan; token baru */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Kata sandi lama salah, atau kata sandi baru sama dengan yang lama */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["TidakBerwenang"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
        };
    };
    list_users: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Akun, superadmin lebih dulu */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"][];
                };
            };
            401: components["responses"]["TidakBerwenang"];
            403: components["responses"]["Terlarang"];
        };
    };
    create_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUserCreate"];
            };
        };
        responses: {
            /** @description Akun dibuat */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserCreated"];
                };
            };
            401: components["responses"]["TidakBerwenang"];
            403: components["responses"]["Terlarang"];
            /** @description Email sudah dipakai, atau level staf tanpa unit */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    delete_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Terhapus */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["TidakBerwenang"];
            403: components["responses"]["Terlarang"];
            404: components["responses"]["TidakDitemukan"];
            /** @description Menghapus diri sendiri, atau superadmin aktif terakhir */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    update_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUserUpdate"];
            };
        };
        responses: {
            /** @description Tersimpan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
            401: components["responses"]["TidakBerwenang"];
            403: components["responses"]["Terlarang"];
            404: components["responses"]["TidakDitemukan"];
            /** @description Melanggar aturan akun (lihat deskripsi) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    reset_user_password: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Kata sandi sementara */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemporaryPassword"];
                };
            };
            401: components["responses"]["TidakBerwenang"];
            403: components["responses"]["Terlarang"];
            404: components["responses"]["TidakDitemukan"];
            /** @description Mengatur ulang akun sendiri */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
